### ISSUE TITLE
Configure Multiple Mikrotik Router?

### ISSUE THREAD

**Issue by saift0014** [EvilFreelancer/routeros-api-php#27]
Can I configure client with multiple mikrotik router? If yes, how and then how to print response from multiple router?

**Comment by EvilFreelancer** [comment]
As you know PHP is synchronous language and that's why the client is able to work with only one router in one moment of time.

And you probably may create loop from array of settings (which will have: user, pass, host for example) which will passed to new object of the client (which will make settings on remote router sequentially).

But if you want know how to configure the parallel operation of several copies of the client with different settings, then probably better ask about this on your PHP framework's forum .

Btw, if you develop on Laravel then you may use `\RouterOS::getClient([settings=>here]);` facade in Laravel Jobs for example.

In any case, your question is not about the library ;)

**Comment by saift0014** [comment]
ok thank you.

**Comment by EvilFreelancer** [comment]
Glad to help, good luck! :)
