### ISSUE TITLE
Are this library can use from outside Router network?

### ISSUE THREAD

**Issue by mthohirin** [EvilFreelancer/routeros-api-php#44]
i'm new in mikrotik, please help

when the device (Phone/Laptop) connected to router, after get `IP & Mac Address` it will redirected to laravel application in cloud server. and then, i need send query for setting that `IP & Mac Address` can connect to internet

so, what query should i use?
or maybe any option for what i need

thank you, sorry for bad english

**Comment by EvilFreelancer** [comment]
Hello! Yes, you can get access to RouterOS from extenal network, but this is not safe.

For access to RouterOS from Internet should be available port of API (without or with encryption).

To check the status just use NMAP via command like `nmap external-address-of-routeros -p 8728,8729` if you will see message like one of these ports is open then library will be able to access to router via API throught this port.

* 8728 - default API port without encryption
* 8729 - default API port with encryption

PS. I would recommend you to close access to RouterOS from internet and implement a VPN tunnel into your network to be able to control the device through the API, because probably in the future some vulnerability may be discovered in the RouterOS API server (like it was with webfig).

**Comment by EvilFreelancer** [comment]
In a nutshell, the library will work if the port of the specified server is open and is the API port, in any other case the library will not work.

**Comment by mthohirin** [comment]
really great answer and recommendation
thank you very much sir
