### ISSUE TITLE
Unable to establish socket connection because the target device actively refused it

### ISSUE THREAD

**Issue by hashweather** [EvilFreelancer/routeros-api-php#55]
I noticed that I can't actually connect to the RouterOS ussing the API unless I have logged in as a user. How can this be resolved?

I want the admin to be able to log in to the router using just the admin password, username and host.

**Comment by EvilFreelancer** [comment]
Hi! Thanks for the report, I have never encountered a similar issue before, it seems you are very lucky :) In any case, I will need to try to reproduce it, please tell me the version of your RouterOS.

**Comment by hashweather** [comment]
I am currently testing this on RouterOS version `6.4.8`

**Comment by EvilFreelancer** [comment]
Unfortunately, I cannot find the firmware of the specified version, probably the problem on your side arises due to the fact that the firmware is too old. I started the project of this library a couple of years ago, then there was a stable version 6.41, I did not conduct tests with earlier firmware.

Most likely, after updating the firmware on your router, the problem will be solved.
