### ISSUE TITLE
How to run mikrotik script

### ISSUE THREAD

**Issue by robiokidenis** [EvilFreelancer/routeros-api-php#84]
I want to run some script inside 

`/system script run REPORT-LIST-CLIENT`

how to write a query for a run of this script?

I have tried to use this 
```
$query = (new Query('/system/script/run'));
        $query->where('name', 'REPORT-LIST-CLIENT');
        $response = $SERVER->query($query)->read();
        
        
```
but it doesn't work.

return 
 ```
"after" => array:1 [▼
    "message" => "script not found"
  ]
```

**Comment by EvilFreelancer** [comment]
Hello! Interesting question, you need to use `equal` instead of `where` for executing scripts.

Another thing about Mikrotik API is: need to use `number` instead of `name`, but number field must contain name you provided.

I've added [a small example](https://github.com/EvilFreelancer/routeros-api-php/blob/master/examples/system_run_script.php#L29-L33) with solution, check it :)

**Comment by robiokidenis** [comment]
thank you, it's Work!
