### ISSUE TITLE
Use /tool/ip-scan address=x.x.x.x

### ISSUE THREAD

**Issue by dkunze** [EvilFreelancer/routeros-api-php#86]
Hello! 

I would like to run the ip-scan command but I am not able to get the MAC address through the IP.
I need to get the MAC address using the IP. 

These are my steps:
`$query = (new Query('/tool/ip-scan'))`

I think this will works. But if I want to add a new parameter like this:

`$query = (new Query('/tool/ip-scan'))->equal('address', '192.168.1.2');`
It won´t work. The error message is:

`Array ( [after] => Array ( [message] => unknown parameter ) )`

Any idea?
Thank you!

**Comment by jonth93** [comment]
IP Scan tool does not have an 'address' parameter. Only 'address-range', which you can specify a single address to get the information you need. Don't forget to set the 'duration' parameter otherwise your API connection will never receive a response and timeout.

If you already know the IP address of the end device that you need the MAC address of, there are couple of alternative ways you can get the mac address, without running the 'ip-scan' tool.

You could have a look at 'ip/neighbour/print' or 'ip/arp/print' with a 'where address=xxx.xxx.xxx.xxx' clause.
If the IP was issued by DHCP, the MAC address will be available as part of the lease.

It's best to run commands through the terminal on the MIkroTik to see what the available parameters are for the command you want to run.

**Comment by dkunze** [comment]
Oh amazing! It worked using the below code:
`$query =(new Query('/ip/arp/print'))->where('address', '192.168.1.2');`

About IP-SCAN, it was working using the terminal on Mikrotik:
`tool ip-scan address=192.168.1.2`
So that was the reason of why I was trying to use it with address.

Anyway, it worked with ip/arp/print. 
Thank you so much!

**Comment by jonth93** [comment]
@dkunze no problem, glad you got it sorted.

Just checked on the terminal using tab to reveal commands.
`tool ip-scan address=192.168.1.2` will work on the terminal ok, but in the API you'll need to set the 'duration' and 'address' will need to be 'address-range'. So in terminal this looks like `tool ip-scan address-range=192.168.1.2 duration=5s`.

For API it will look like:
`$query =  (new Query('/tool/ip-scan'))->equal('address-range', '192.168.1.2')->equal('duration', '5s')`

**Comment by dkunze** [comment]
You are amazing @jonth93 ! I really appreciate your time, your answer is very useful to me! Thank you so much! It worked with **ip-scan** too, thank you dude!

**Comment by ArtMin96** [comment]
@jonth93 Hi. I have a quick question. Do you know how I can monitor (upload/download) specific IP addresses? I don't know which API I should call. Thanks

**Comment by EvilFreelancer** [comment]
@ArtMin96 hello! Check this example https://github.com/EvilFreelancer/routeros-api-php/blob/master/examples/monitoring.php

**Comment by ArtMin96** [comment]
@EvilFreelancer This is interface monitoring. I want a specific IP address monitoring.

**Comment by EvilFreelancer** [comment]
@ArtMin96 hi! I don't it is possible out of box, you can detect only traffic on interfaces, for detecting recipients of traffic need to use something like tcpdump.

But in any case transport level (OSI L2) is know nothing about ip addresses.

**Comment by ArtMin96** [comment]
@EvilFreelancer Thanks
